"""added indiviual product details

Revision ID: 96f7f13c90e0
Revises: 
Create Date: 2025-05-03 00:00:26.002583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f7f13c90e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('releasedate', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('availabity', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('availabity')
        batch_op.drop_column('releasedate')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
