name: 🧪 Run Tests (Node.js Backend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x]  # stable Node versions

    steps:
      # Step 1: Checkout repo
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4
        with: 
          fetch-depth : 0

      # Step 2: Setup Node.js
      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies inside backend_node
      - name: 📥 Install Dependencies
        working-directory: backend_node
        run: npm ci

      # Step 4: Run Jest tests inside backend_node
      - name: 🧪 Run Jest Tests
        working-directory: backend_node
        env:
          NODE_ENV: test
        run: npm test -- --runInBand --detectOpenHandles
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      # Deploy using Render API
      - name: 🚀 Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering deploy on Render..."
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":true}' \
            https://api.render.com/v1/services/srv-d45ou0ripnbc738qgbsg/deploys
